### ISSUE TITLE
Other layout requirements

### ISSUE THREAD

**Issue by r12a** [w3c/dpub-pagination#1]
why no mention of other layout requirement initiatives besides LatinReq, especially those that relate to the Asian features under consideration?

for a summary of other relevant layout requirements work see
http://www.w3.org/International/layout

**Comment by dauwhe** [comment]
I've added an explicit mention of JLReq, and linked to the list of layout requirements documents you mentions. Thanks very much!

**Comment by r12a** [comment]
What should also help is a link to the relevant section of our typography index, eg. for vertical text that would be http://w3c.github.io/typography/#vertical_text

that's what that index was designed for, actually.

**Comment by r12a** [comment]
i believe this is done in http://w3c.github.io/dpub-pagination/priorities.html, so closing.
