### ISSUE TITLE
What Latin means

### ISSUE THREAD

**Issue by r12a** [w3c/dpub-pagination#6]
[developed from an original comment by Leslie Sikos]

https://www.w3.org/TR/2014/WD-dpub-latinreq-20140930/#abstract

> This document describes requirements for pagination and layout of books in latin languages

This should say "This document describes requirements for pagination and layout of books in languages that use the Latin script"

We may have missed it, but we think that the document should explain quite early that Latin script languages means more than just English or other languages that use ASCII or even Latin1 characters.

**Comment by dauwhe** [comment]
Closed via 8eff76f

Thanks @r12a!
